name: shelf_api
description: A sample command-line application.
version: 1.0.0
publish_to: none
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.3.0

# Add regular dependencies here.
dependencies:
  dart_jsonwebtoken: ^2.13.0
  dotenv: ^4.2.0
  envied: ^0.5.3
  json_annotation: ^4.8.1
  postgres: ^3.1.1
  shelf: ^1.4.1
  shelf_cors_headers: ^0.1.5
  shelf_di:
    path: packages/shelf_di
  shelf_router: ^1.1.4
  supabase: ^2.0.8

dev_dependencies:
  build_runner: ^2.4.8
  envied_generator: ^0.5.3
  json_serializable: ^6.7.1
  lints: ^3.0.0
  test: ^1.24.0
